### ISSUE TITLE
브랜드 | 상품 등록 / 수정 페이지

### ISSUE THREAD

**Issue by ruehan** [jae-hyeon-and-children/sponer#7]
# Description
브랜드는 상품에 대한 정보를 입력 후 `상품 등록하기` 버튼을 눌러 상품을 등록할 수 있다.

### 페이지 관련

- 로그인을 안 한 상태일 경우 : 로그인 페이지로 이동
- 로그인을 했는데 브랜드가 아닐 경우 : 메인 페이지로 이동

### 상품 form 관련
- 데이터가 모두 입력되지 않았다면 상품을 등록할 수 없다.

![Image](https://github.com/jae-hyeon-and-children/sponer/assets/65541546/65834b84-19e0-4c73-b9b0-87398e283e89)

# Additional
- [ ] 맞춤 키 option 값들 정하기
- [ ] 이미지 순서 바꿀 수 있음. 첫 번째가 대표 이미지가 됨
- [ ] server actions

**Comment by ruehan** [comment]
이미지 등록 / 삭제 / 순서 변경에 문제는 없으나 삭제 클릭 시 파일 선택 창이 팝업되는 문제가 있음

https://github.com/jae-hyeon-and-children/sponer/assets/65541546/16505a93-9d17-4794-bd03-c6be9f9342cc

**Comment by ruehan** [comment]
API 연결까지 구현 완료

**Comment by Ujaa** [comment]
한규님 천재다

**Comment by SonSETO** [comment]
한국이란 나라는 한규를 담기엔 너무 좁다.
